# Generated by Django 5.0.3 on 2024-03-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapi.category', verbose_name='Категорія продукту'),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_sell', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(related_name='products_in_basket', to='productsapi.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapi.subcategory', verbose_name='Підкатегорія продукту'),
        ),
        migrations.AddField(
            model_name='category',
            name='owned_subcategorys',
            field=models.ManyToManyField(to='productsapi.subcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_tags',
            field=models.ManyToManyField(to='productsapi.tag'),
        ),
    ]
