# Generated by Django 5.0.3 on 2024-03-16 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='purchaser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='Покупець'),
        ),
        migrations.AddField(
            model_name='payments',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
    ]
